[general]
first_superuser = "sb"
first_superuser_password = "getmein"
environment = "development"
log_level = "INFO"
origins = [ "http://localhost:3000", "localhost:3000", "http://localhost:3006", "localhost:3006", "localhost", "https://stage1.shiftboolean.com", "https://stage2.shiftboolean.com", "https://dev1.shiftboolean.com", "https://dev2.shiftboolean.com", "https://demo1.shiftboolean.com", "https://demo2.shiftboolean.com", "https://127.0.0.1:5500", "http://127.0.0.1:5500", "https://widget.shiftboolean.com", "https://widget2.shiftboolean.com", "https://widget4.shiftboolean.com", "https://widget5.shiftboolean.com", "https://widget3.shiftboolean.com", "https://widget8.shiftboolean.com", "https://widget06.shiftboolean.com", "http://15.206.188.120:8011", "http://15.206.188.120:8012", "https://admin.apollouniversity.edu.in", "https://dashboard.apollouniversity.edu.in", "https://admin.headstart.biz", "https://dashboard.headstart.biz", "http://20.204.39.242:8011", "http://20.204.39.242:8012", "https://tawk.to",]

[master_db]
db_username = "aristo"
db_password = "L1G1qC8axe5SpaYG"
db_url = "clientauto.mxs2q.mongodb.net"
db_name = "master_db"



[base_path]
base_path_api = "http://127.0.0.1:8000/"
base_path = "dev1.headstart.biz"
base_admin_path = "dev2.headstart.biz/"

[random]
password_str = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890abcdefghijklmnopqrstuvwxyz"
random_otp = "1234567890987654321"
random_name = "1234567890abcdefghijklmnopqrstuvwxyz"

[authentication]
secret_key_auth = "43d22d57646176744b6d31afdf47a4a55e3277135c201ff449258af417cf9e99"
algorithm = "HS256"

[testing]
test = false

[Google_recaptcha]
captcha_site_key = "6LfFENUfAAAAAH4Dh_lx49xi6IqCA1QytPCpkrT5"
captcha_secret_key = "6LfFENUfAAAAAGDkvGZdUEhxhrOhklUkWkA0nFbp"

[redis_server]
redis_server_url = "redis://:uJkY3a9nWs2g5bVt@dev273gq.shiftboolean.com:6379/0"

[teamcity_credential]
teamcity_base_path = "https://teamcity.shiftboolean.com"
teamcity_build_type = "ReportsGtcrmDev_GenerateReports"
teamcity_token = "eyJ0eXAiOiAiVENWMiJ9.aG9PMS1EU3hRaFlwbjZrOEcybExjbDFuSDVz.ZTdkNzQ5YTgtMzY4OC00YmZiLWIxODktODE3ZjlkMzk0ZDkz"

[env]
aws_env = "dev"

[pool_db]
max_pool_size = 50
min_pool_size = 0

[rate_limiting]
rate_limit_type = "api_wise"
public_limit_count = 50000000000000000000
private_limit_count = 250000000000000000000
global_limit_count = 500000000000000000000
advance_public_limit_count = 1500000000000000
advance_private_limit_count = 2500000000000000
advance_global_limit_count = 5000000000000000

[pgsql_db]
pgsql_username = "gtcrmtestadmin"
pgsql_password = "qcjJjyKafV%40cc"
pgsql_host = "gtcrm-postgres-test.postgres.database.azure.com"
pgsql_port = 5432
pgsql_name = "GTCRM"

[rabbit_mq]
rmq_username = "raptor"
rmq_password = "Dy!.7D8iNqwnfa$"
rmq_url = "maino.shiftboolean.in"
rmq_host = "my_vhost"
rmq_port = "5672"
rmq_email_queue = "Email_service_queue"

[api_security]
user_name = "sb"
password = "qtv3Bq7VaUR$9MeU754S"
