""" This File Contains the Schema for the Approval System """
from datetime import datetime
from typing import Optional, Union

from bson import ObjectId
from pydantic import BaseModel, Field


# Todo: Add Request Body Data Validation after the Finalization of Approval Workflows


class NewApprovalRequestModel(BaseModel):
    approval_type: str
    # Todo: Add the Request Body Data Validation after the Finalization of Approval Workflows & API Endpoints for pushing the
    #  Data in the Database
    payload: Union[dict, list]


class UpdateApprovalRequestModel(BaseModel):
    approval_data: Union[dict, list]


class RemarksModel(BaseModel):
    remarks: str

class SystemFields(BaseModel):
    """
    Schema for System Fields which are Generated by System & Added to Client Information
    """
    id: Optional[ObjectId] = Field(default_factory=ObjectId, alias="_id")
    status: Optional[str] = "pending"
    submitted_by: ObjectId
    submitted_by_name: str
    submitted_by_email: str
    submitted_by_mobile: str
    submitted_by_org_name: Optional[str] = None
    client_id: Optional[ObjectId] = None
    college_id: Optional[ObjectId] = None
    created_at: Optional[datetime] = Field(default_factory=datetime.now)
    updated_at: Optional[datetime] = Field(default_factory=datetime.now)
    approvals: Optional[list] = []
    current_approvers: list
    current_level: int
    previous_timeline: list = []

    class Config:
        """
        Configuration for Schema
        """
        arbitrary_types_allowed = True

class ApprovalFilterModel(BaseModel):
    approval_type: list = []
    approval_status: list = []
    client_ids: list = []
    college_ids: list = []