name: Automatic Labeler
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: labeler-${{ github.ref }}
  cancel-in-progress: false

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      # Create Label based on files changed
      - name: Create Label
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
