name: Daily Cleanup of Azure Resources

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

concurrency:
  group: cleanup-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

env:
  AZURE_WEBAPP_PREFIX: gtcrm-api- # The prefix you use for naming Azure Web Apps and Resource Groups

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup Azure Resources
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get list of open pull requests
        id: open_prs
        run: |
          echo "Fetching list of open PRs..."
          pr_list=$(gh pr list --state open --json number --jq '.[].number' --repo ${{ github.repository }} | xargs)
          echo "Fetched PRs: $pr_list"
          if [ -z "$pr_list" ]; then
            echo "OPEN_PRS=''" >> $GITHUB_ENV
          else
            echo "OPEN_PRS=$pr_list" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Cleanup Azure Resources
        run: |
          echo "Starting cleanup..."
          for rg in $(az group list --query "[?starts_with(name, '${{ env.AZURE_WEBAPP_PREFIX }}')].name" -o tsv); do
            # Extract the PR number from the resource group name
            pr_number=${rg#"${{ env.AZURE_WEBAPP_PREFIX }}"}
            pr_number=${pr_number%-rg} # Assuming your resource group names end with -rg

            # Check if the extracted PR number is in the list of open PRs
            if [[ ! " ${{ env.OPEN_PRS }} " =~ " $pr_number " ]]; then
              echo "Deleting resource group: $rg"
              az group delete --name "$rg" --no-wait --yes
            else
              echo "Skipping active resource group: $rg"
            fi
          done
        env:
          AZURE_WEBAPP_PREFIX: gtcrm-api-
          OPEN_PRS: ${{ env.OPEN_PRS }}
